DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS quizzes;
DROP TABLE IF EXISTS users;

SET @@auto_increment_increment=1;

CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE quizzes (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  owner_id INTEGER NOT NULL,
  name varchar(255) NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_owner FOREIGN KEY ( owner_id ) REFERENCES users( id ) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE questions (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  quiz_id INTEGER NOT NULL,
  question varchar(255) NOT NULL,
  answer varchar(255) NOT NULL,
  correct BOOLEAN NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_quiz FOREIGN KEY ( quiz_id ) REFERENCES quizzes( id ) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE scores (
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  quiz_id INTEGER NOT NULL,
  score_val INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_owner_score FOREIGN KEY ( user_id ) REFERENCES users( id ) ON DELETE CASCADE,
  CONSTRAINT fk_quiz_score FOREIGN KEY ( quiz_id ) REFERENCES quizzes( id ) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;